from __future__ import annotations

from openpyxl import Workbook

from inventory_cover.io.excel_io import detect_header_row_in_sheet, map_headers
from inventory_cover.utils.text_cleaning import normalize_header


def test_header_normalization_removes_case_spaces_and_punctuation() -> None:
    assert normalize_header(" External_ID ") == "externalid"
    assert normalize_header("Model-Numebr!") == "modelnumebr"


def test_variant_column_names_map_to_canonical_fields() -> None:
    headers = [
        "PO",
        "Vendor",
        "ASIN",
        "External Id",
        "Model Numebr",
        "Availibility",
        "Accepted Quantity",
        "Total Cost",
    ]

    mapping = map_headers(headers)

    assert mapping["Vendor Code"] == 1
    assert mapping["External ID"] == 3
    assert mapping["Model Number"] == 4
    assert mapping["Availability"] == 5
    assert mapping["Quantity Accepted"] == 6
    assert mapping["Total Cost"] == 7


def test_header_row_detection_skips_intro_rows() -> None:
    wb = Workbook()
    ws = wb.active
    ws.title = "PurchaseOrderItems"
    ws.append(["Amazon Vendor Central export"])
    ws.append(["Generated by report"])
    ws.append(
        [
            "PO",
            "Vendor Code",
            "ASIN",
            "External ID",
            "Model Number",
            "Title",
            "Availability",
            "Window Type",
            "Window Start",
            "Window End",
            "Expected Date",
            "Quantity Requested",
            "Quantity Accepted",
            "Quantity Received",
            "Quantity Outstanding",
            "Unit Cost",
            "Total Cost",
        ]
    )

    detection = detect_header_row_in_sheet(ws)

    assert detection is not None
    assert detection.header_row == 3
    assert detection.missing_required == []
